@ cdecl hid_close(ptr)
@ cdecl hid_enumerate(long long)
@ cdecl hid_error(ptr)
@ cdecl hid_exit()
@ cdecl hid_free_enumeration(ptr)
@ cdecl hid_get_feature_report(ptr str long)
@ cdecl hid_get_indexed_string(ptr long wstr long)
@ cdecl hid_get_manufacturer_string(ptr wstr long)
@ cdecl hid_get_product_string(ptr wstr long)
@ cdecl hid_get_serial_number_string(ptr wstr long)
@ cdecl hid_init()
@ cdecl hid_open(long long wstr)
@ cdecl hid_open_path(str)
@ cdecl hid_read(ptr str long)
@ cdecl hid_read_timeout(ptr str long long)
@ cdecl hid_send_feature_report(ptr str long)
@ cdecl hid_set_nonblocking(ptr long)
@ cdecl hid_write(ptr str long)
